name: Release Unity Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create PlayKit SDK package
        uses: natsuneko-laboratory/create-unitypackage@v3
        with:
          files-glob: |
            Packages/com.playkit.sdk/**/*
          dest: PlayKitSDK_v${{ steps.get_version.outputs.VERSION }}.unitypackage

      - name: Create Steam Addon package
        uses: natsuneko-laboratory/create-unitypackage@v3
        with:
          files-glob: |
            Packages/com.playkit.sdk.steam/**/*
          dest: PlayKitSDK-Steam_v${{ steps.get_version.outputs.VERSION }}.unitypackage

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            PlayKitSDK_v${{ steps.get_version.outputs.VERSION }}.unitypackage
            PlayKitSDK-Steam_v${{ steps.get_version.outputs.VERSION }}.unitypackage
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
