name: Release Unity Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create PlayKit SDK package
        uses: pCYSl5EDgo/create-unitypackage@v1
        with:
          package-path: PlayKitSDK.unitypackage
          include-files: |
            Packages/com.playkit.sdk

      - name: Create Steam Addon package
        uses: pCYSl5EDgo/create-unitypackage@v1
        with:
          package-path: PlayKitSDK-Steam.unitypackage
          include-files: |
            Packages/com.playkit.sdk.steam

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            PlayKitSDK.unitypackage
            PlayKitSDK-Steam.unitypackage
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
